# Generated by Django 5.2.4 on 2025-08-10 06:32

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/', verbose_name='صورة السلايدر')),
                ('slide_name', models.CharField(max_length=255, verbose_name='عنوان السلايدر')),
                ('slide_description', models.TextField(blank=True, null=True, verbose_name='وصف السلايدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logos/', validators=[website.models.validate_file_extension])),
                ('youtube', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('whatsapp', models.CharField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('location_map_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
