# Generated by Django 5.2.3 on 2025-08-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.option'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.size'),
        ),
    ]
